INSERT INTO `productos`(`codigo`, `categoria`, `descripcion`, `distribuidor`, `enlace`, `fabricante`, `imagen`, `marca`, `material`, `nombre`, `precio`)
VALUES
('FG001', 'figuras', 'Una figura detallada que captura la valentía y la carga del Portador del Anillo. Ideal para quienes aprecian al héroe más inesperado de la Tierra Media', 'Lord of the Rings Toys', 'producto-detalle.html?codigo=FG001', 'Lord of the Rings Toys', '/img/productos/IMAGENES_DE_FIGURAS/frodoIMGchetaaPNG.png', 'Lord of the Rings Toys', 'Plastico de calidad', 'Frodo', 29990),
('FG002', 'figuras', 'Una figura detallada que captura la sabiduría y el poder del mago más icónico de la Tierra Media', 'Lord of the Rings Toys', 'producto-detalle.html?codigo=FG002', 'Lord of the Rings Toys', '/img/productos/IMAGENES_DE_FIGURAS/gandaflIMGcheta.png', 'Lord of the Rings Toys', 'Plastico de calidad', 'Gandalf el gris', 39990),
('FG003', 'figuras', 'Figura del enano Gimli con todos sus detalles característicos, ideal para los amantes de la Tierra Media', 'Lord of the Rings Toys', 'producto-detalle.html?codigo=FG003', 'Lord of the Rings Toys', '/img/productos/IMAGENES_DE_FIGURAS/gimliIMGcheta.jpg', 'Lord of the Rings Toys', 'Plastico de calidad', 'Gimli', 49990),
('FG004', 'figuras', 'Figura de Legolas con su arco y flechas, perfecta para los coleccionistas de la Tierra Media', 'Lord of the Rings Toys', 'producto-detalle.html?codigo=FG004', 'Lord of the Rings Toys', '/img/productos/IMAGENES_DE_FIGURAS/figuraDeLegolas.webp', 'Lord of the Rings Toys', 'Plastico de calidad', 'Legolas', 59990),
('JM001', 'juegos_de_mesa', 'Un clásico juego de estrategia donde los jugadores compiten por colonizar y expandirse en la isla de Catan. Ideal para 3-4 jugadores y perfecto para noches de juego en familia o con amigos.', 'Distribuidora Catan', 'producto-detalle.html?codigo=JM001', 'Catan Studio', '/img/productos/IMAGENES_JUEGOS_DE_MESA/catan.webp', 'Catan Studio', 'Cartón y plástico de calidad', 'Catan', 29990),
('JM002', 'juegos_de_mesa', 'Un juego de colocación de fichas donde los jugadores construyen el paisaje alrededor de la fortaleza medieval de Carcassonne. Ideal para 2-5 jugadores y fácil de aprender.', 'Devir Chile', 'producto-detalle.html?codigo=JM002', 'Rio Grande Games', '/img/productos/IMAGENES_JUEGOS_DE_MESA/CARCASSONE.webp', 'Rio Grande Games', 'Cartón y fichas de madera', 'Carcassonne', 24990),
('AC001', 'accesorios', 'Ofrece una experiencia de juego cómoda con botones mapeables y una respuesta táctil mejorada. Compatible con consolas Xbox y PC.', 'Xbox Chile', 'producto-detalle.html?codigo=AC001', 'Xbox', '/img/productos/img_accesorios/control_xbox.jpg', 'Xbox', 'Plástico y componentes electrónicos', 'Controlador Inalámbrico Xbox Series X', 59990),
('AC002', 'accesorios', 'Proporcionan un sonido envolvente de calidad con un micrófono desmontable y almohadillas de espuma viscoelástica para mayor comodidad durante largas sesiones de juego', 'HyperX Chile', 'producto-detalle.html?codigo=AC002', 'HyperX', '/img/productos/img_accesorios/audi_gamer_hx_cloud2.jpg', 'HyperX', 'Plástico, cuero sintético y componentes electrónicos', 'Auriculares Gamer HyperX Cloud II', 74990),
('CO001', 'consolas', 'La consola de última generación de Sony, que ofrece gráficos impresionantes y tiempos de carga ultrarrápidos para una experiencia de juego inmersiva.', 'Sony Chile', 'producto-detalle.html?codigo=CO001', 'Sony', '/img/productos/img_consolas/playstation5.png', 'Sony', 'Plástico y componentes electrónicos', 'PlayStation 5', 549990),
('CG001', 'pc_gamer', 'Un potente equipo diseñado para los gamers más exigentes, equipado con los últimos componentes para ofrecer un rendimiento excepcional en cualquier juego.', 'Asus Chile', 'producto-detalle.html?codigo=CG001', 'Asus', '/img/productos/img_pcgamers/pc_gamer_asus_strix.png', 'Asus', 'Metal, plástico y componentes electrónicos', 'PC Gamer ASUS ROG Strix', 1299990),
('SG001', 'sillas_gamer', 'Diseñada para el máximo confort, esta silla ofrece un soporte ergonómico y personalización ajustable para sesiones de juego prolongadas.', 'Secret Lab', 'producto-detalle.html?codigo=SG001', 'Secret Lab', '/img/productos/img_sillas_gamer/Silla Gamer Secretlab Titan.jpg', 'Secret Lab', 'Cuero sintético y espuma de alta densidad', 'Silla Gamer Secretlab Titan', 349990),
('MS001', 'mouse', 'Con sensor de alta precisión y botones personalizables, este mouse es ideal para gamers que buscan un control preciso y personalización.', 'Logitech Chile', 'producto-detalle.html?codigo=MS001', 'Logitech', '/img/productos/img_mouse/Mouse_Gamer_Logitech_G502_HERO.jpg', 'Logitech', 'Plástico y componentes electrónicos', 'Mouse Gamer Logitech G502 HERO', 49990),
('MP001', 'mousepad', 'Ofrece un área de juego amplia con iluminación RGB personalizable, asegurando una superficie suave y uniforme para el movimiento del mouse.', 'Razer', 'producto-detalle.html?codigo=MP001', 'Razer', '/img/productos/img_mousepad/Mousepad_Razer_Goliathus_Extended_Chroma.webp', 'Razer', 'Tela y base de goma antideslizante', 'Mousepad Razer Goliathus Extended Chroma', 29990),
('PP001', 'poleras_personalizadas', 'Una camiseta cómoda y estilizada, con la posibilidad de personalizarla con tu gamer tag o diseño favorito.', 'Level-Up Gamer', 'producto-detalle.html?codigo=PP001', 'Level-Up Gamer', '/img/productos/img_poleras_personalizadas/polera_level_up.png', 'Level-Up Gamer', 'Algodón de alta calidad', 'Polera Gamer Personalizada ''Level-Up''', 14990);